server:
  port: 8083

spring:
  application:
    name: ms-bodega
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/db_bodega?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:lumina_user}
    password: ${SPRING_DATASOURCE_PASSWORD:lumina_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

bodega:
  stock-critico-umbral: 10
