server:
  port: 8080

spring:
  application:
    name: msal-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/f7592987-1fb4-4045-afea-34bb5a3fe9d7/v2.0
          # GUID (v2.0) y Application ID URI.
          audiences:
            - api://262adf80-2a1e-4193-a2bc-df28650eb1bc
            - 262adf80-2a1e-4193-a2bc-df28650eb1bc

logging:
  level:
    org.springframework.security.oauth2: DEBUG