server:
  port: 8080

spring:
  application:
    name: bff-gateway

# URLs de los microservicios
microservices:
  usuarios:
    url: ${MS_USUARIOS_URL:http://localhost:8081}
  productos:
    url: ${MS_PRODUCTOS_URL:http://localhost:8082}
  bodega:
    url: ${MS_BODEGA_URL:http://localhost:8083}
  carrito:
    url: ${MS_CARRITO_URL:http://localhost:8084}
  delivery:
    url: ${MS_DELIVERY_URL:http://localhost:8085}
  pagos:
    url: ${MS_PAGOS_URL:http://localhost:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info
